'use client';
import {useEffect,useState} from 'react';
import type {SavedFilter} from '@/lib/owner-storage';
import {emptyCriteria,type FilterCriteria} from '@/lib/saved-filter';
export default function SavedFilters({sources,onApply}:{sources:string[];onApply:(criteria:FilterCriteria|null)=>void}){
 const [filters,setFilters]=useState<SavedFilter[]>([]),[name,setName]=useState(''),[criteria,setCriteria]=useState<FilterCriteria>({...emptyCriteria}),[active,setActive]=useState(true),[id,setId]=useState<string>(),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const abort=new AbortController();fetch('/api/saved-filters',{cache:'no-store',signal:abort.signal}).then(async r=>{if(!r.ok)throw Error('Uložené filtry nejsou dostupné. Zkontroluj přístup majitele a databázi.');const data=await r.json() as {filters:SavedFilter[]};setFilters(data.filters);setReady(true)}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Načítání selhalo')});return()=>abort.abort()},[]);
 function edit(filter:SavedFilter){setId(filter.id);setName(filter.name);setActive(filter.active);setCriteria({...emptyCriteria,...filter.criteria} as FilterCriteria)}
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/saved-filters'+(id?'?id='+encodeURIComponent(id):''),{method:id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,criteria,active})});const data=await r.json() as {filter:SavedFilter;error?:string};if(!r.ok)throw Error(data.error||'Uložení selhalo');setFilters(prev=>[data.filter,...prev.filter(x=>x.id!==data.filter.id)]);setId(data.filter.id)}catch(e){setError(e instanceof Error?e.message:'Uložení selhalo')}finally{setBusy(false)}}
 async function remove(filter:SavedFilter){setBusy(true);setError('');try{const r=await fetch('/api/saved-filters?id='+encodeURIComponent(filter.id),{method:'DELETE'});if(!r.ok)throw Error('Smazání selhalo');setFilters(prev=>prev.filter(x=>x.id!==filter.id));if(id===filter.id){setId(undefined);setName('')}}catch(e){setError(e instanceof Error?e.message:'Smazání selhalo')}finally{setBusy(false)}}
 return <section className="panel"><h2>Moje uložené filtry</h2>{error&&<p role="alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={!ready||busy}><div className="auction-controls"><div><label htmlFor="filter-name">Název filtru</label><input id="filter-name" required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></div><div><label htmlFor="filter-location">Lokalita</label><input id="filter-location" value={criteria.location} onChange={e=>setCriteria({...criteria,location:e.target.value})}/></div><div><label htmlFor="filter-type">Typ nemovitosti</label><select id="filter-type" value={criteria.propertyType} onChange={e=>setCriteria({...criteria,propertyType:e.target.value})}><option value="">Všechny</option><option value="house">Dům / chata</option><option value="apartment">Byt</option><option value="land">Pozemek</option><option value="garage">Garáž</option><option value="other">Budova / stavba</option></select></div><div><label htmlFor="filter-min">Cena od (Kč)</label><input id="filter-min" type="number" min="0" value={criteria.minPrice??''} onChange={e=>setCriteria({...criteria,minPrice:e.target.value===''?null:Number(e.target.value)})}/></div><div><label htmlFor="filter-max">Cena do (Kč)</label><input id="filter-max" type="number" min="0" value={criteria.maxPrice??''} onChange={e=>setCriteria({...criteria,maxPrice:e.target.value===''?null:Number(e.target.value)})}/></div><div><label htmlFor="filter-source">Zdroj</label><select id="filter-source" value={criteria.source} onChange={e=>setCriteria({...criteria,source:e.target.value})}><option value="">Všechny</option>{sources.map(s=><option key={s}>{s}</option>)}</select></div></div><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Aktivní hlídač</label><p className="meta">Podmínky se ukládají do databáze. Automatická upozornění zatím nejsou zapojená.</p><button type="submit">{busy?'Ukládám…':id?'Uložit změny':'Uložit filtr'}</button><button type="button" onClick={()=>{setId(undefined);setName('');setCriteria({...emptyCriteria});setActive(true)}}>Nový filtr</button></fieldset></form>{filters.map(filter=><div className="source-item" key={filter.id}><span>{filter.name} · {filter.active?'aktivní':'neaktivní'}</span><div><button type="button" disabled={busy} onClick={()=>onApply({...emptyCriteria,...filter.criteria} as FilterCriteria)}>Použít</button><button type="button" disabled={busy} onClick={()=>edit(filter)}>Upravit</button><button type="button" disabled={busy} onClick={()=>void remove(filter)}>Smazat</button></div></div>)}<button type="button" onClick={()=>onApply(null)}>Zrušit uložený filtr v přehledu</button></section>
}
