export type Listing={source:string;title:string;url:string;date:string;published:string;price:string;location:string;msk:boolean;status:string};
const region=/(?:moravskoslezsk|ostrav(?:a|ě|y)|karvin(?:á|é|ou)|havířov|bohumín|orlová|český těšín|frýdek.místek|třinec|opav(?:a|ě)|krnov|bruntál|nový jičín|kopřivnic(?:e|i)|rymařov|rýmařov|příbor|rychvald|komorní lhotka|milíkov|šilheřovic|jablunkov|frenštát|bílovec|fulnek|hlučín|petřvald|dolní lutyn|čeladn|frýdlant nad ostravic)/i;
const property=/(?:nemovit|pozem|parcel|rodinn|dům|domu|byt\b|bytov|budov|stavb|garáž|jednotk|chata|chalup)/i;
function decode(s:string){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&(?:amp|lt|gt|quot|apos|nbsp|#x[\da-f]+|#\d+);/gi,v=>{const m:Record<string,string>={'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&apos;':"'",'&nbsp;':' '};if(m[v])return m[v];let n=0;if(/^&#x/i.test(v))n=parseInt(v.slice(3,-1),16);else if(/^&#/.test(v))n=parseInt(v.slice(2,-1),10);return n>0&&n<0x110000?String.fromCodePoint(n):v}).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
function safeLink(value:string,base:string){try{const u=new URL(decode(value),base);return u.protocol==='https:'?u.href:''}catch{return ''}}
async function get(url:string,max=1_600_000){const res=await fetch(url,{signal:AbortSignal.timeout(18000),headers:{'Accept':'text/html, application/json, application/rss+xml, */*','User-Agent':'ISIR-Reality-MSK/1.0'}});if(!res.ok)throw Error('HTTP '+res.status);const len=Number(res.headers.get('content-length')||0);if(len>max)throw Error('Příliš velká odpověď');const body=await res.text();if(body.length>max)throw Error('Příliš velká odpověď');return {body,res}}
function unique(a:Listing[]){return [...new Map(a.filter(x=>x.url&&x.title).map(x=>[x.url,x])).values()]}
export async function cevd(msk:boolean):Promise<Listing[]>{const p=new URLSearchParams({take:msk?'100':'60',skip:'0',categoryIds:'1',eventStartDateFrom:new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Prague'}),orderBy:'auction.publicationDate desc'});if(msk)p.set('regionIds','132');const {body}=await get('https://cevd.gov.cz/api/auctions/items?'+p,4_000_000);const j=JSON.parse(body) as {items:Array<{id:number;name:string;status:string;startingBid:number|null;description?:string;auction:{eventStart?:string;publicationDate?:string;status?:string;number?:string}}>};if(!Array.isArray(j.items))throw Error('Neplatná odpověď CEVD');return j.items.map(x=>({source:'CEVD',title:x.name||'Nemovitost',url:'https://cevd.gov.cz/seznam-drazeb/detail/'+x.id,date:x.auction?.eventStart||'',published:x.auction?.publicationDate||'',price:x.startingBid?`${x.startingBid.toLocaleString('cs-CZ')} Kč`:'',location:x.name||'',msk:msk||region.test((x.name||'')+' '+(x.description||'').slice(0,500)),status:x.status||x.auction?.status||''})).filter(x=>x.status==='Published'&&x.url)}
export async function financial():Promise<Listing[]>{const {body}=await get('https://financnisprava.gov.cz/cs/financni-sprava/drazby-financni-spravy/drazby-prehled?rss=1');if(!/<rss\b/i.test(body))throw Error('Neplatný RSS');const out:Listing[]=[];for(const m of body.matchAll(/<item>([\s\S]*?)<\/item>/gi)){const field=(k:string)=>decode(new RegExp('<'+k+'>([\\s\\S]*?)<\\/'+k+'>','i').exec(m[1])?.[1]||'');const title=field('description'),location=title,url=safeLink(field('link'),'https://financnisprava.gov.cz');if(!property.test(title)||!url.startsWith('https://financnisprava.gov.cz/'))continue;out.push({source:'Finanční správa',title,url,date:field('pubDate'),published:'',price:'',location,msk:region.test(location),status:'Aktuální v RSS'})}return unique(out)}
export async function okdrazby():Promise<Listing[]>{const base='https://okdrazby.cz/';const {body}=await get(base);const a:Listing[]=[];for(const m of body.matchAll(/<a[^>]+class="AuctionsList_auctionName[^"\n]*"[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi)){const title=decode(m[2]);if(!property.test(title))continue;const tail=body.slice(m.index,m.index+850);const date=decode(/AuctionsList_auctionExactDateTime[^>]*>(.*?)<\/span>/i.exec(tail)?.[1]||'');const url=safeLink(m[1],base);a.push({source:'OKdražby',title,url,date,published:'',price:'',location:title,msk:region.test(title),status:'Zveřejněno na portálu'})}return unique(a)}
export async function prokonzulta():Promise<Listing[]>{const base='https://www.prokonzulta.cz/nabidky';const {body}=await get(base);const a:Listing[]=[];for(const m of body.matchAll(/<a\s+href="(https:\/\/www\.prokonzulta\.cz\/(?:drazba|aukce|prodej)\/[^" ]+)"[^>]*>[\s\S]{0,1800}?<h3 class="offer-label">([\s\S]*?)<\/h3>/gi)){const title=decode(m[2]),url=safeLink(m[1],base);if(!property.test(title))continue;a.push({source:'Prokonzulta',title,url,date:'',published:'',price:'',location:title,msk:region.test(title),status:'Zveřejněno na portálu'})}return unique(a)}
export async function asis():Promise<Listing[]>{const base='https://portal.asis.cz/Katalog/-/1/';const {body}=await get(base);const a:Listing[]=[];for(const m of body.matchAll(/<a\s+href="([.\/]*Majetek\/Detail\/[^" ]+)"[^>]*>([\s\S]*?)<\/a>[\s\S]{0,170}?<p[^>]*>([\s\S]*?)<\/p>/gi)){const title=decode(m[3])||decode(m[2]);const url=safeLink(m[1],base);a.push({source:'ASIS – insolvenční majetek',title,url,date:'',published:'',price:'',location:title,msk:region.test(title),status:'Zveřejněno na portálu'})}return unique(a)}
export async function karvina():Promise<Listing[]>{const base='https://aukce.karvina.cz/';const {body}=await get(base);const a:Listing[]=[];for(const m of body.matchAll(/<div[^>]+class="[^"]*drazbaitem\s+([^"]+)"[\s\S]*?<a href="(https:\/\/aukce\.karvina\.cz\/drazba\/[^" ]+)"[^>]*>\s*<h4>([\s\S]*?)<\/h4>/gi)){if(/ended|ukončen/i.test(m[1]))continue;const title=decode(m[3]),url=safeLink(m[2],base);a.push({source:'Aukce města Karviná',title,url,date:'',published:'',price:'',location:'Karviná',msk:true,status:'Aktivní aukce'})}return unique(a)}
export async function portalDrazeb(msk:boolean):Promise<Listing[]>{
 const base='https://www.portaldrazeb.cz/drazby';
 const {body,res}=await get(base);
 const csrf=/<meta name="csrf-token" content="([^"]+)"/.exec(body)?.[1];
 const cookie=res.headers.get('set-cookie')?.split(';')[0];
 if(!csrf||!cookie)throw Error('Relace portálu není dostupná');
 const pageSize=100,maxPages=5,a:Listing[]=[];
 const filter:Record<string,unknown>={category:[1],sort:'desc',sort_by:'published_at',limit:pageSize,offset:0};
 if(msk)filter.county_item=['Ostrava-město','Karviná','Frýdek-Místek','Opava','Nový Jičín','Bruntál'];
 for(let page=0;page<maxPages;page++){
  filter.offset=page*pageSize;
  const response=await fetch(base+'.json',{method:'PUT',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrf,'Cookie':cookie},body:JSON.stringify({filter}),signal:AbortSignal.timeout(18000)});
  if(!response.ok)throw Error('Portál dražeb HTTP '+response.status);
  const raw=await response.text();
  if(raw.length>3_000_000)throw Error('Příliš velká odpověď');
  const j=JSON.parse(raw) as Record<string,unknown>;
  const entries=Object.entries(j).filter(([key,value])=>/^\d+$/.test(key)&&!!value&&typeof value==='object');
  for(const [,value] of entries){
   const x=value as {item?:{title?:string;category?:{full_path?:string};location_district?:{district_name?:string;county?:{county_name?:string}}};status?:string;link?:string;start_at?:string;published_at?:string;item_price?:number};
   const title=decode(x.item?.title||''),url=safeLink(x.link||'',base),location=x.item?.location_district?.district_name||title;
   if(!x.item?.category?.full_path?.startsWith('/Nemovitosti')||!url||x.status==='finished')continue;
   a.push({source:'Portál dražeb',title,url,date:x.start_at||'',published:x.published_at||'',price:x.item_price?`${x.item_price.toLocaleString('cs-CZ')} Kč`:'',location,msk:msk||x.item?.location_district?.county?.county_name==='Moravskoslezský kraj'||region.test(title),status:x.status||'Aktuální'});
  }
  if(entries.length<pageSize)break;
 }
 return unique(a)
}
export async function portalElektronickych(msk:boolean):Promise<Listing[]>{const base='https://www.portal-elektronickych-drazeb.cz'+(msk?'/kraj-moravskoslezsky/':'/drazby/');const {body}=await get(base);const a:Listing[]=[];for(const m of body.matchAll(/<div class="drazba-home">[\s\S]{0,700}?<div class="drazba-title"><a href="([^"]+)">([\s\S]*?)<\/a>/gi)){const title=decode(m[2]),url=safeLink(m[1],base);a.push({source:'Portál elektronických dražeb',title,url,date:'',published:'',price:'',location:title,msk:msk||region.test(title),status:'Zveřejněno na portálu'})}return unique(a)}
export async function drazbyProst():Promise<Listing[]>{const base='https://www.drazbyprost.cz/';const {body}=await get(base);const a:Listing[]=[];for(const m of body.matchAll(/<h2[^>]*><a href="(\/\d+-[^" ]+)"[^>]*>([\s\S]*?)<\/a><\/h2>/gi)){const title=decode(m[2]),url=safeLink(m[1],base);if(!property.test(title))continue;a.push({source:'DražbyProst',title,url,date:'',published:'',price:'',location:title,msk:region.test(title),status:'Zveřejněno na portálu'})}return unique(a)}
export async function elektronickeDrazby():Promise<Listing[]>{const base='https://www.elektronickedrazby.cz/';const {body}=await get(base);const a:Listing[]=[];for(const m of body.matchAll(/<div class='a-holder' data-href='(\/view\/\d+)'[\s\S]{0,850}?<h4><strong>([\s\S]*?)<\/strong><\/h4>/gi)){const title=decode(m[2]),url=safeLink(m[1],base);if(!property.test(title))continue;a.push({source:'Elektronické dražby',title,url,date:'',published:'',price:'',location:title,msk:region.test(title),status:'Zveřejněno na portálu'})}return unique(a)}
export async function uzsvm(msk:boolean):Promise<Listing[]>{const response=await fetch('https://www.nabidkamajetku.gov.cz/api/Property/AuctionList',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ListType:'all',Page:1,PageSize:msk?100:65,Order:'PublishedFrom',OrderDesc:'true',CategoryId:0,LocalityId:msk?'r0008':0}),signal:AbortSignal.timeout(18000)});if(!response.ok)throw Error('ÚZSVM HTTP '+response.status);const raw=await response.text();if(raw.length>4_000_000)throw Error('Příliš velká odpověď');const data=JSON.parse(raw) as {Auctions:Array<{Id:number;Name:string;CategoryName:string;DistrictName?:string;Price?:string;StartDate?:string;UpdatedDate?:string;StatusName?:string}>};if(!Array.isArray(data.Auctions))throw Error('Neplatná odpověď ÚZSVM');const districts=['Ostrava-město','Karviná','Frýdek-Místek','Opava','Nový Jičín','Bruntál'];return data.Auctions.filter(x=>/pozem|stavb|byt|dům|nemovit|garáž|jednotk|budov/i.test(x.CategoryName||'')).map(x=>({source:'ÚZSVM – aukce majetku',title:x.Name,url:`https://www.nabidkamajetku.gov.cz/Home/AuctionDetail/${x.Id}`,date:x.StartDate||'',published:x.UpdatedDate||'',price:x.Price?`${x.Price} Kč`:'',location:x.DistrictName||'',msk:districts.includes(x.DistrictName||''),status:x.StatusName||'Aktuální nabídka'}))}
export async function insolvencniZamery():Promise<Listing[]>{const base='https://www.portaldrazeb.cz/insolvencni-zamery';const {body}=await get(base,4_000_000);const encoded=/data-intentions="([^"]+)"/.exec(body)?.[1];if(!encoded)throw Error('Seznam záměrů není dostupný');const records=JSON.parse(decode(encoded)) as Array<{title:string;hash:string;status:string;publishedAt:string;monetizationTo?:string;minimumPrice?:number;item:{category?:string;location?:{county?:{name?:string};city?:{name?:string}}}}>;if(!Array.isArray(records))throw Error('Neplatný seznam záměrů');return records.filter(x=>x.item?.category?.startsWith('Nemovitosti')&&x.status!=='finished').map(x=>({source:'Insolvenční záměry',title:x.title,url:safeLink('/insolvencni-zamer/'+x.hash,base),date:x.monetizationTo||'',published:x.publishedAt||'',price:x.minimumPrice?`${x.minimumPrice.toLocaleString('cs-CZ')} Kč`:'',location:x.item.location?.city?.name||x.title,msk:x.item.location?.county?.name==='Moravskoslezský kraj'||region.test(x.title),status:'Záměr ke zpeněžení'}))}
export async function exdrazby(msk:boolean):Promise<Listing[]>{
 const filters:Array<{property:string;operator:string;value:string|number}>=[{property:'auction.status',operator:'eq',value:'prepared'}];
 if(msk)filters.push({property:'auctionAddress.region',operator:'eq',value:14});
 const params=new URLSearchParams({page:'1',perPage:'100',sort:JSON.stringify({property:'auction.timeCreated',direction:'DESC'}),filter:JSON.stringify(filters)});
 const {body}=await get('https://exdrazby.cz/api/web/auction/?'+params,4_000_000);
 const data=JSON.parse(body) as {data:Array<{id:number;title:string;startDt?:string;minimalBid?:number;parentStatus?:string;statusTranslation?:string;auctionCategory?:{parentTitle?:string};auctionAddress?:{city?:string;region?:{name?:string}}}>};
 if(!Array.isArray(data.data))throw Error('Neplatná odpověď exdrazby');
 return data.data.filter(x=>x.parentStatus==='prepared'&&x.auctionCategory?.parentTitle==='Nemovitosti').map(x=>({source:'exdrazby',title:x.title,url:`https://www.exdrazby.cz/drazba/${x.id}`,date:x.startDt||'',published:'',price:x.minimalBid?`${x.minimalBid.toLocaleString('cs-CZ')} Kč`:'',location:x.auctionAddress?.city||'',msk:x.auctionAddress?.region?.name==='Moravskoslezský kraj',status:x.statusTranslation||'Připravovaná dražba'}));
}
export async function spravaZeleznic():Promise<Listing[]>{
 const base='https://iframe.ipp.spravazeleznic.cz/prodeje-pronajmy/api/iframe/advertisements';
 const {body}=await get(base+'?PaymentType=Sell&pageSize=100',4_000_000);
 const result=JSON.parse(body) as {data:Array<{id:number;name:string;address?:string;region?:string;paymentType?:string;offerType?:string;publishFrom?:string;publishTo?:string;price?:number;showPrice?:boolean}>};
 if(!Array.isArray(result.data))throw Error('Neplatná odpověď Správy železnic');
 const now=new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Prague'});
 return result.data.filter(x=>x.paymentType==='Sell'&&!!x.publishFrom&&x.publishFrom.slice(0,10)<=now&&(!x.publishTo||x.publishTo.slice(0,10)>=now)).map(x=>({source:'Správa železnic – prodej',title:x.name,url:`https://www.spravazeleznic.cz/nemovitosti/inzerat?id=${x.id}`,date:x.publishTo||'',published:x.publishFrom||'',price:x.showPrice&&x.price?`${x.price.toLocaleString('cs-CZ')} Kč`:'',location:x.address||'',msk:x.region==='Moravskoslezský kraj',status:x.offerType==='ETender'?'Elektronická aukce':'Výběrové řízení'}));
}
export async function drazbyExekutori():Promise<Listing[]>{
 const base='https://www.drazby-exekutori.cz/nove-drazby.aspx';const {body}=await get(base);
 const out:Listing[]=[];
 for(const m of body.matchAll(/<table\b[^>]*class="tblDrazbaMala"[\s\S]*?<a href="(\/DR\d+\/[^" ]+\/?)"[^>]*class="linkDrazbaMala"[\s\S]*?<h3>([\s\S]*?)<\/h3>[\s\S]*?<span id="zacatekDrazby">([^<]*)<\/span>[\s\S]*?<\/table>/gi)){
  const title=decode(m[2]),url=safeLink(m[1],base),date=decode(m[3]);if(!property.test(title)||!url)continue;
  out.push({source:'dražby-exekutoři',title,url,date,published:'',price:'',location:title,msk:region.test(title),status:'Připravovaná dražba'});
 }
 return unique(out);
}
