export type AuctionSource={name:string;url:string;category:string;note?:string;live?:boolean};
export const auctionSources:AuctionSource[]=[
 {name:'Portál dražeb Exekutorské komory',live:true,url:'https://www.portaldrazeb.cz/drazby',category:'Exekuce',note:'Centrální přehled nařízených exekučních dražeb'},
 {name:'CEVD',live:true,url:'https://cevd.gov.cz/seznam-drazeb',category:'Veřejné dražby',note:'Neobsahuje dražby soudních exekutorů ani správců daně'},
 {name:'Finanční správa',url:'https://financnisprava.gov.cz/cs/financni-sprava/drazby-financni-spravy/drazby-prehled',category:'Stát',live:true,note:'Živý přehled využívá zveřejněné RSS'},
 {name:'Celní správa',url:'https://celnisprava.gov.cz/cz/drazby/Stranky/default.aspx',category:'Stát',note:'Jednotlivé vyhlášky; automatické rozlišení nemovitostí se připravuje'},
 {name:'ÚZSVM – Nabídka majetku',live:true,url:'https://www.nabidkamajetku.gov.cz/Home/Auctions?ListType=all',category:'Stát'},
 {name:'Insolvenční záměry – Portál dražeb',live:true,url:'https://www.portaldrazeb.cz/insolvencni-zamery',category:'Insolvence',note:'Také přímý prodej a výběrová řízení'},
 {name:'Asociace insolvenčních správců',live:true,url:'https://portal.asis.cz/Katalog/-/1/',category:'Insolvence'},
 {name:'Insolvenční majetek',url:'https://insolvencnimajetek.cz/',category:'Insolvence'},
 {name:'ISIR – původní spisy',url:'https://isir.justice.cz/isir/common/index.do',category:'Insolvence',note:'Rejstřík spisů, nikoli katalog aktuálních dražeb'},
 {name:'OKdražby',live:true,url:'https://okdrazby.cz/',category:'Dražební portály'},
 {name:'exdrazby',live:true,url:'https://www.exdrazby.cz/',category:'Dražební portály',note:'Připravované dražby nemovitostí'},
 {name:'dražby-exekutoři',live:true,url:'https://www.drazby-exekutori.cz/nove-drazby.aspx',category:'Dražební portály',note:'První stránka nových dražeb'},
 {name:'Portál elektronických dražeb',live:true,url:'https://www.portal-elektronickych-drazeb.cz/drazby/',category:'Dražební portály'},
 {name:'Prokonzulta',live:true,url:'https://www.prokonzulta.cz/nabidky',category:'Dražební portály'},
 {name:'DražbyProst',live:true,url:'https://www.drazbyprost.cz/',category:'Dražební portály'},
 {name:'Drazby.cz',url:'https://www.drazby.cz/nabidka-drazeb/',category:'Dražební portály'},
 {name:'Elektronické dražby',live:true,url:'https://www.elektronickedrazby.cz/',category:'Dražební portály'},
 {name:'Ostrava – úřední deska',url:'https://ostrava.cz/cs/urad/uredni-deska',category:'MSK a další prodeje',note:'Záměry prodeje města mohou být bez dražby'},
 {name:'Karviná – městské aukce',live:true,url:'https://aukce.karvina.cz/',category:'MSK a další prodeje'},
 {name:'Lesy ČR – nepotřebný majetek',url:'https://lesycr.cz/o-nas/prodej-nepotrebneho-majetku/',category:'MSK a další prodeje',note:'Prodeje a výběrová řízení mimo jednotný katalog dražeb'},
 {name:'Správa železnic – prodej',live:true,url:'https://www.spravazeleznic.cz/nemovitosti/prehled',category:'MSK a další prodeje',note:'Výběrová řízení a aukce na prodej, bez pronájmů'},
];
