import assert from 'node:assert/strict';
import {emptyCriteria,matchesSavedFilter,validateSavedFilter} from './saved-filter.ts';
const filter={name:' Ostrava domy ',active:true,criteria:{...emptyCriteria,location:'Ostrava',propertyType:'house',minPrice:1000000,maxPrice:5000000}};
assert.equal(validateSavedFilter(filter).name,'Ostrava domy');
for(const bad of [{...filter,name:''},{...filter,active:'true'},{...filter,criteria:{...filter.criteria,minPrice:-1}},{...filter,criteria:{...filter.criteria,minPrice:6000000}},{...filter,criteria:{...filter.criteria,maxPrice:Infinity}},{...filter,criteria:{...filter.criteria,propertyType:'unsupported'}}])assert.throws(()=>validateSavedFilter(bad));
const item={title:'Rodinný dům v Ostravě',location:'Ostrava',price:'4 500 000 Kč',source:'CEVD'};
assert.equal(matchesSavedFilter(item,filter.criteria),true);
assert.equal(matchesSavedFilter({...item,price:''},filter.criteria),false);
assert.equal(matchesSavedFilter({...item,price:'6 000 000 Kč'},filter.criteria),false);
assert.equal(matchesSavedFilter({...item,title:'Byt',location:'Ostrava'},filter.criteria),false);
assert.equal(matchesSavedFilter(item,{...emptyCriteria,source:'exdrazby'}),false);
assert.equal(matchesSavedFilter(item,{...emptyCriteria,location:'ostrava'}),true);
console.log('saved filters: validation, price bounds, unknown prices, type, locality and source passed');
